name: Notificacoes

on:
  schedule:
    - cron: "0 12 * * *"   # 09:00 horário de Brasília
    - cron: "0 18 * * *"   # 15:00 horário de Brasília
    - cron: "0 23 * * *"   # 20:00 horário de Brasília
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v3

      - name: Instalar Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install

      - name: Executar script de notificações
        env:
          FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
        run: node index.js
